export const playList = {
  music: [
    {
      title: 'Hello Radio 90.8',
      album: 'Malayalam',
      artist: 'Kidney federation of India',
      genre: 'Malayalam',
      source: 'http://148.72.210.73:8000/helloradio.ogg',
      image:
        'http://www.kidneyvoice.com/wp-content/uploads/2019/07/small-logo.png',
      trackNumber: 1,
      totalTrackCount: 1,
      duration: 9999,
      site: 'http://www.helloradio.in/',
      id: 'helloradio'
    },
    {
      title: 'Theeram Radio',
      album: 'Malayalam',
      artist: 'Theeram',
      genre: 'Malayalam',
      source: 'http://titan.shoutca.st:8647/stream',
      image: 'https://radiosindia.com/images/theeramradio.jpg',
      trackNumber: 2,
      totalTrackCount: 1,
      duration: 9999,
      site: 'http://radiosindia.com/theeramradio.html',
      id: 'theeram'
    },
    {
      title: 'WHTZ-FM - Z100',
      album: 'live',
      artist: 'International',
      genre: 'English',
      source: 'http://c5icyelb.prod.playlists.ihrhls.com/1469_icy',
      image: 'https://upload.wikimedia.org/wikipedia/en/e/e2/WHTZ_logo.png',
      trackNumber: 3,
      totalTrackCount: 1,
      duration: 9999,
      site: 'http://whtzfm.radio.net/',
      id: 'whtz'
    },
    {
      title: 'Shakti FM',
      album: 'Tamil',
      artist: 'Shakti',
      genre: 'Tamil',
      source: 'http://live.trusl.com:1160/stream/1/',
      image: 'https://cdn.webrad.io/images/logos/onlineradios-in/shakti.png',
      trackNumber: 4,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://onlineradios.in/shakti/',
      id: 'shakti'
    },
    {
      title: 'Radio Mirchi 98.3',
      album: 'Hindi',
      artist: 'Radio Mirchi',
      genre: 'Hindi',
      source: 'http://peridot.streamguys.com:7150/Mirchi',
      image: 'https://cdn.webrad.io/images/logos/onlineradios-in/mirchi-fm.png',
      trackNumber: 5,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://onlineradios.in/mirchi-fm/',
      id: 'mirchi'
    },
    {
      title: 'Club FM UAE',
      album: 'Malayalam',
      artist: 'Club FM',
      genre: 'Malayalam',
      source: 'http://20073.live.streamtheworld.com/CLUBFMUAEAAC.aac',
      image: 'https://radiosindia.com/images/clubfm.jpg',
      trackNumber: 6,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/clubfm.html',
      id: 'club'
    },
    {
      title: 'Asianet Radio Dubai',
      album: 'Malayalam',
      artist: 'Asianet Radio',
      genre: 'Malayalam',
      source: 'http://54.38.73.80:9060/hqstream',
      image: 'https://radiosindia.com/images/asianetradio.jpg',
      trackNumber: 7,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/asianetradio.html',
      id: 'asianet'
    },
    {
      title: 'Radio Kerala',
      album: 'Malayalam',
      artist: 'Radio Kerala',
      genre: 'Malayalam',
      source: 'https://eu9.fastcast4u.com/proxy/snxwobze?mp=/1',
      image: 'https://radiosindia.com/images/radiokerala.jpg',
      trackNumber: 8,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/radiokerala.html',
      id: 'radiokerala'
    },
    {
      title: 'Gaanam Radio',
      album: 'Malayalam',
      artist: 'Gaanam Radio',
      genre: 'Malayalam',
      source: 'http://5.79.88.132:7104/;',
      image:
        'https://cdn.webrad.io/images/logos/onlineradios-in/ganam-malayalam.png',
      trackNumber: 9,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://onlineradios.in/region/malayalam/#ganam-malayalam',
      id: 'gaanamradio'
    },
    {
      title: 'Tulip Radio',
      album: 'Telugu',
      artist: 'Tulip Radio',
      genre: 'Telugu',
      source: 'http://perseus.shoutca.st:8141/stream',
      image: 'https://radiosindia.com/images/tulipradio.jpg',
      trackNumber: 10,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/tulipradio.html',
      id: 'tulippradio'
    },
    {
      title: 'AIR Malayalam',
      album: 'Malayalam',
      artist: 'AIR Malayalam',
      genre: 'Malayalam',
      source: 'http://51.15.208.163:8081/radio/airmalayalam/icecast.audio',
      image: 'https://radiosindia.com/images/air.jpg',
      trackNumber: 11,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/airmalayalam.html',
      id: 'airmalayalam'
    },
    {
      title: 'Radio Mango UAE',
      album: 'Malayalam',
      artist: 'Radio Mango',
      genre: 'Malayalam',
      source: 'http://51.15.208.163:8081/radio/RadioMango_1/icecast.audio',
      image: 'https://radiosindia.com/images/radiomango.jpg',
      trackNumber: 12,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/radiomango.html',
      id: 'radiomangouae'
    },
    {
      title: 'Mazhavil FM UAE',
      album: 'Malayalam',
      artist: 'Mazhavil FM UAE',
      genre: 'Malayalam',
      source: 'http://mazhavilfm.out.airtime.pro:8000/mazhavilfm_a',
      image: 'https://radiosindia.com/images/mazhavilfm.jpg',
      trackNumber: 13,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/mazhavilfm.html',
      id: 'mazhavilfmuae'
    },
    {
      title: 'Suryan UAE',
      album: 'Tamil',
      artist: 'Suryan FM',
      genre: 'Tamil',
      source: 'http://209.133.216.3:7071/;stream.mp3',
      image: 'https://radiosindia.com/images/suryanfm.jpg',
      trackNumber: 14,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/suryanfm.html',
      id: 'suryanfm'
    },
    {
      title: 'Radio City Tamil',
      album: 'Tamil',
      artist: 'Radio City Tamil',
      genre: 'Tamil',
      source: 'http://prclive1.listenon.in:9948/;',
      image: 'https://radiosindia.com/images/radiocity.jpg',
      trackNumber: 15,
      totalTrackCount: 1,
      duration: 9999,
      site: 'https://radiosindia.com/radiocitytamil.html',
      id: 'radiocitytamil'
    }
  ]
}
